spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
      access-key: LTAI5tA1zWkqZPUUuSUjATNZ
      secret-key: KD301L5rRCvZV0cLXvx2jqJbus8ITy
      bucket: alen-bucket
server:
  port: 20000