spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.125.174:3306/eaglemall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rj1183
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: yueshop-ware
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000